### PR TITLE
Fix chain ids in extension

### LINKED ISSUE #1680: Replace `chainIdRecord` with a solution that requires adding the chain ID only when necessary for certain extension functionality. Additionally, provide clear guidance on where to obtain the value for a new chain ID.
When adding a new chain, I need to provide a new value for `chainIdRecord`, even though it may not be necessary. For example, when adding Zcash, I had to input a seemingly random string that holds no significance. Please consider a better solution. Additionally, we already have a record of EVM chain IDs in numeric format, which can be converted to hexadecimal if needed.

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1680 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **Refactor**
	- Improved handling and validation of supported blockchain types, focusing on EVM and Cosmos chains.
	- Streamlined logic for chain ID extraction and assignment, reducing redundancy and clarifying behavior when connecting dApps.
	- Simplified chain ID management by dynamically generating IDs and refining session state types.
	- Added existence checks to prevent errors when resolving chain IDs during wallet operations.
	- Introduced separate chain ID mappings and lookup functions for Cosmos and EVM chains, enhancing clarity and accuracy.
	- Updated wallet and messaging logic to explicitly differentiate between Cosmos and EVM chain kinds.
	- Converted chain ID formats between hexadecimal strings and numeric values for better API compatibility.
	- Added utility functions for hex-to-number and number-to-hex conversions to support chain ID formatting.
- **Bug Fixes**
	- Enhanced error handling for unsupported chain types, ensuring more predictable responses during account and chain switching operations.

### CODE REVIEW

File: clients/extension/src/pages/connect-dapp/index.tsx [hunk 1]
```diff
@@ -45,21 +46,26 @@ export const ConnectDAppPage = () => {
...
     await setCurrentVaultId(vaultId)
+
     await addSession({
       vaultId: vaultId,
       session: {
         host: getDappHostname(sender),
         url: getDappHost(sender),
-        chainIds: [getChainId(chain)],
+        chainIds: chainId ? [chainId] : undefined,
         selectedCosmosChainId:
```
Comment (rcoderdev) [inline clients/extension/src/pages/connect-dapp/index.tsx:66]: That's messy. It should be clear that we support both 'evm' and 'cosmos' chains here, and we should have a single selectedChainId, correct?

File: core/chain/chains/cosmos/chainInfo.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  [CosmosChain.TerraClassic]: 'columbus-5',
+  [CosmosChain.Noble]: 'noble-1',
+  [CosmosChain.Akash]: 'akashnet-2',
+}
+
+export const getCosmosChainId = (chain: CosmosChain): string => {
+  return cosmosChainId[chain]
+}
+
+export const getCosmosChainByChainId = (chainId: string): Chain | undefined => {
```
Comment (rcoderdev) [inline core/chain/chains/cosmos/chainInfo.ts:20]: We have a `mirrorRecord` utility. Please check the examples of its usage.

File: core/chain/chains/evm/chainInfo.ts [hunk 3]
```diff
@@ -59,3 +59,12 @@ export const evmChainInfo = recordMap(
 export const getEvmChainId = (chain: EvmChain): number => {
   return evmChainInfo[chain].id
 }
+
+export const getEvmChainByChainId = (chainId: string): Chain | undefined => {
```
Comment (rcoderdev) [inline core/chain/chains/evm/chainInfo.ts:63]: Same here, we can use mirrorRecord
