### PR TITLE
Fix app lock passcode issue

### LINKED ISSUE #2006: [BUG] -  "Error: 'Unsupported state or unable to authenticate data' After Entering Passcode"
Description:
"Error: 'Unsupported state or unable to authenticate data' After Entering Passcode"

**Steps to Reproduce:**

1. Navigate to the "Security" settings.
2. Click the "Change Passcode" button to open the Change Passcode form.
3. Enter the existing passcode.
4. Enter the new passcode and confirm it.
5. Click the "Save" button.

**Expected Result:** The passcode should be successfully changed and the user should receive a confirmation message.
Actual Result: 
**Screenshots**

Image

https://github.com/user-attachments/assets/e1b396d1-138c-437c-810c-a13729f6d6eb

**Desktop (please complete the following information):**
 - OS: Chrome Ext v0.2.2
 - Browser - Chromed

**Additional context**
` at RootCurrentVaultProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:44892:46)
    at provider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:15556:30)
    at provider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:3176:30)
    at CurrentVaultIdProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:44863:44)
    at provider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:3176:30)
    at ErrorBoundary (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:329411:7)
    at RootErrorBoundary (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:329550:39)
    at provider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:15556:30)
    at I18nextProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:5182:36)
    at I18nProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:334892:37)
    at MatchQuery (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:45404:32)
    at StorageDependant (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:334912:38)
    at MatchQuery (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:45404:32)
    at StorageMigrationsManager (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:328748:46)
    at Wrap (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:328974:26)
    at MatchQuery (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:45404:32)
    at WalletCoreProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:104148:94)
    at QueryClientProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:10007:39)
    at provider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:3176:30)
    at ot (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:4409:19)
    at Ye (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:4254:37)
    at ThemeProvider (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:329254:114)
    at CoreApp (chrome-extension://ggafhcdaplkhmmnlbfjpnnkepdfjaelb/index.js:335025:27)`

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

Fix app lock passcode in extension 

Fixes #2006 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Refactor**
  * Improved reliability of passcode validation by updating internal logic for handling passcode state and assertions.
  * Removed an unused passcode assertion hook to streamline state management.
  * Enhanced clarity in passcode-related operations for better maintainability.
  * Simplified state handling by removing a custom hook that enforced non-null state values.

* **Chores**
  * Updated internal dependencies and import paths for consistency.

### CODE REVIEW

**Review by rcoderdev — CHANGES_REQUESTED** [review]
Perhaps I’m missing something, but this PR doesn’t seem to make any changes. Have you been able to reproduce the issue prior to these changes?

File: lib/ui/state/usePresentState.ts [hunk 1]
```diff
@@ -6,8 +6,8 @@ type NonNullableSetStateAction<T> = T | null | ((prevState: T) => T)
 export const usePresentState = <T>([state, setState]: [
   T | null,
   Dispatch<SetStateAction<T | null>>,
-]): [T, Dispatch<NonNullableSetStateAction<T>>] => {
-  const presentState = useMemo(() => shouldBePresent(state), [state])
+]): [T | null, Dispatch<NonNullableSetStateAction<T>>] => {
```
Comment (rcoderdev) [inline lib/ui/state/usePresentState.ts:9]: That undermines the entire concept of the hook; we want to ensure that value is present and clearly asserted.

**Comment by Ehsan-saradar** [comment]
> Collaborator
> ###

It works quite fine on extension, you can spend a few minutes and test it 
Artifact download URL: https://github.com/vultisig/vultisig-windows/actions/runs/16343141792/artifacts/3553693226

**Review by rcoderdev — APPROVED** [review]
