### PR TITLE
Fix fast vault overview title and missing word and style

### LINKED ISSUE #2267: [BUG Figma vs Wind & Ext] - Fast Vault / Vault Overview / Server – Incorrect Labels, Title, Font Styling, and Missing Word
**Summary:**
On Windows and Chrome Extension, multiple inconsistencies are observed compared to the Figma design:

1. The framework shows the label as “Part 1” instead of “Share 1.”
2. The title is shown as “Vault Overview” instead of “Back Up Part 1.”
3. A font gradient has been added to the word “preferably,” which is not present in the Figma design.
4. The word “Device” is missing in the sentence where it appears in the Figma file.

**Design Reference:**
Figma design: *Vultisig App – Fast Vault / Vault Overview / Server*
[Figma Link](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=3-1510&p=f&t=kXePi3pHuLAIZNbP-0)

image

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

Fixes #2267

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- New Features
  - Added a reusable StepFlow layout for header/content/footer flows.

- Refactor
  - Migrated onboarding and multiple backup slides to StepFlow with unified header/footer, updated progress indicators (including a new 4-step variant) and streamlined navigation.
  - Improved step navigation guards and disabled forward actions while loading to prevent out-of-bounds advancement.

- Localization
  - Updated English copy/keys (added "Backup Share 2", clarified "securely, preferably"/"to ensure access, preferably", "this device vault share").

- Style
  - Standardized 28px step text and introduced layout positioning support affecting container positioning.

- Chores
  - Replaced many relative imports with absolute module paths.

### CODE REVIEW

File: core/ui/onboarding/components/OnboardingSteps.tsx [hunk 1]
```diff
@@ -25,134 +26,107 @@ export const OnboardingSteps: FC<OnFinishProp> = ({ onFinish }) => {
...
-            kind="link"
-            onClick={!currentAnimation ? goBack : handlePrevAnimation}
-            size="sm"
+    <StepFlow
+      content={<AnimationComponent />}
+      footer={
+        <>
+          <AnimatedVisibility>
+            {match(currentAnimation, {
+              1: () => (
```
Comment (rcoderdev) [inline core/ui/onboarding/components/OnboardingSteps.tsx:37]: It feels off this 1, 2, 3, 4, 5. Maybe we should create an array of those steps and access the current slide by its index?

**Review by rcoderdev — APPROVED** [review]
Good, small comments
