### PR TITLE
Fix setting menu

### LINKED ISSUE #1604: [BUG] Separating settings for Extension and windows
**Describe the bug**
As windows and ther Extension will have a few different features, there will be different settings. Therefore we need to separate the windows settings from the extension settings. Otherwise there will be features like "Expand View" in the windows version.

**Expected behavior**

- [ ] Have Extension and Windows settings separated

**Desktop (please complete the following information):**
 - Version 23

### LINKED ISSUE #1605: [ADD] Extension settings
Please follow the [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=37942-61534&t=M6kN8njFJjbVkzOH-4) for general Setting implementation:

Image

Specific Cases:

- [ ] Do not implement Vault settings, a separate issue will be opened for it
- [ ] Prioritize Vultisig: If enabled, overwrite all extensions we are injecting on, if disabled 
- [ ] Hide Referral for the moment

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

- Commented out the referral item
- Removed default chains
- Removed `Expand View` in Windows
- Added option to show advanced settings after clicking the build number 5 times
 
Fixes #1604 
Fixes #1605 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
  - Added a hidden advanced modal for managing MPC library settings in the desktop app, accessible by clicking the build number five times.
  - Introduced an "Expand View" option in the extension settings to open the extension in a new tab or window.

- **Improvements**
  - Settings pages now adapt their content based on platform (desktop or extension), showing relevant options for each.

- **Removals**
  - Removed the ability to manage default blockchain chains from the user interface.
  - Removed the dedicated advanced DKLS settings page in the desktop app.

### CODE REVIEW

File: clients/desktop/src/components/manage-dkls/index.tsx [hunk 1]
```diff
@@ -0,0 +1,46 @@
+import { useVaultCreationMpcLib } from '@clients/desktop/src/mpc/state/vaultCreationMpcLib'
+import { UnstyledButton } from '@lib/ui/buttons/UnstyledButton'
+import { Switch } from '@lib/ui/inputs/switchControlContainer'
+import { Modal } from '@lib/ui/modal'
+import { useRef, useState } from 'react'
+import { useTranslation } from 'react-i18next'
+
+export const ManageDkls = () => {
```
Comment (rcoderdev) [inline clients/desktop/src/components/manage-dkls/index.tsx:8]: I believe we have a different strategy for locating files. We use logical locations instead of kind-based locations at the top level. For example, the old page was located in mpc/dkls because it is related to this domain, rather than being categorized under components. Instead of sorting everything into components/hook/utils, we aim to organize files based on their domain area. You can see this approach in the core package, for instance.

File: core/ui/settings/index.tsx [hunk 2]
```diff
@@ -131,29 +132,28 @@ export const SettingsPage: FC<SettingsPageProps> = ({
...
-              <ListItem
-                icon={<ExpandIcon fontSize={20} />}
-                onClick={() =>
-                  openUrl(`chrome-extension://${chrome.runtime.id}/index.html`)
-                }
-                title={t('expand_view')}
-                hoverable
-                showArrow
-              />
+              {mpcDevice !== 'windows' && mpcDevice !== 'extension' && (
```
Comment (rcoderdev) [inline core/ui/settings/index.tsx:135]: We combine two solutions: passing props for customizations and examining mpcDevices. Which makes it confusing, which should I use when doing another customization?

Comment (rcoderdev) [reply core/ui/settings/index.tsx:135]: To modify the content of sections, clients should specify what should be displayed. For example, the extension will adjust the defaults by adding priorities at the top of the first section and including an expanded view at the end of the current section.

Comment (rcoderdev) [reply core/ui/settings/index.tsx:135]: We should avoid using `mpcDevice` for conditional rendering. While I believe we also build the desktop client for Linux, we do not manage that, and `mpcDevice` is always set to Windows. 

If we want to customize based on the client, we should introduce a new hook that returns the client type, which would be either `extension` or `desktop`. We can then use this information for matching. For now, this hook can simply check the value of `mpcDevice`: if it indicates an extension, it should return `extension`; otherwise, it should return `desktop`. However, I still think it would be better to implement customizable content sections.

**Review by rcoderdev — CHANGES_REQUESTED** [review]
Good, settings page needs improvements

File: clients/desktop/src/components/manage-dkls/index.tsx (hunk 1 above)
Comment (Ehsan-saradar) [reply clients/desktop/src/components/manage-dkls/index.tsx]: Fixed

File: core/ui/settings/index.tsx [hunk 3]
```diff
@@ -39,24 +38,28 @@ import { useToast } from '@lib/ui/toast/ToastProvider'
...
+  expandView: ReactNode
+  prioritize: ReactNode
 }
 
-export const SettingsPage: FC<SettingsPageProps> = ({
-  checkUpdate,
-  prioritize,
-}) => {
+interface WindowsSettings {
+  client: Extract<MpcDevice, 'windows'>
```
Comment (rcoderdev) [inline core/ui/settings/index.tsx:48]: It's good, but let's consider adding a new type instead of using `MpcDevice`, which might also be `linux`. For example, we could introduce a `Client` type that could be either `extension` or `desktop`.

Comment (rcoderdev) [reply core/ui/settings/index.tsx:48]: That will also match how we name clients in the clients folder of our repo

**Review by rcoderdev — APPROVED** [review]
Good, small comments

File: core/ui/settings/index.tsx (hunk 2 above)
Comment (Ehsan-saradar) [reply core/ui/settings/index.tsx]: Updated

File: core/ui/settings/index.tsx (hunk 3 above)
Comment (Ehsan-saradar) [reply core/ui/settings/index.tsx]: Updated
