### PR TITLE
Remove: 0x prefix from thorchain tx hash

### LINKED ISSUE #1747: [BUG] Remove 0x prefix for THORChain tx
**Describe the bug**
Currently the app produces the `0x` prefix for tx ids coming from THORChain, where it does not have these prefixes on chain

**Expected behavior**

- [ ] No `0x `prefix on THORChain tx
- [ ] No `0x` prefix on MAYA ty

**Screenshots**

Image

**Desktop (please complete the following information):**
 - Version m main branch

### PR DESCRIPTION
**Pull request by devzl**
## Description

Please include a summary of the change and which issue is fixed. 
Remove 0x prefix from thorchain tx hash
Fixes #1747 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [x] Sending  - Please attach a tx link here https://thorchain.net/tx/AD3FEE89ACCE97CDC69C43CC39F02A6D3FB1FC530C06545BAD753FA5BBDBB98A
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
  - Improved transaction hash display by including blockchain chain context for more accurate normalization across supported chains.

- **Bug Fixes**
  - Enhanced handling of transaction hash prefixes for specific chains, ensuring correct formatting for THORChain and MayaChain transactions.

### CODE REVIEW

File: core/ui/mpc/keysign/utils/normalizeTxHash.ts [hunk 1]
```diff
@@ -1,14 +1,18 @@
+import { Chain } from '@core/chain/Chain'
+
 const memoKeywords = ['switch', 'merge', 'channel']
+const no0xChains = ['THORChain', 'MayaChain']
 
 export const normalizeTxHash = (
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/utils/normalizeTxHash.ts:6]: Okay, let's merge it for now. I will make a note to remove this function altogether later, as it is the responsibility of the function returning the transaction hash to eliminate this prefix. However, please avoid hardcoding chains like this. For instance, in this case, you could use `isOneOf(chain, Object.values(VaultBasedCosmosChain))`.

**Review by rcoderdev — APPROVED** [review]
