### PR TITLE
Fix THORChain unbond / Leave doesn't sign issue

### LINKED ISSUE #1023: [BUG] THORChain unbond / leave command doesn't sign with IOS device
**Describe the bug**
When constructing an unbond / leave message on THORChain , it can't cosign with an ios device

### PR DESCRIPTION
**Pull request by johnnyluo**
Fixes #1023 

## Summary by CodeRabbit

- **Bug Fixes**
  - Streamlined the deposit process so that certain transactions no longer require an input amount, ensuring consistent handling.
  - Set default transaction amounts explicitly to improve validation during deposit operations.

- **Refactor**
  - Adjusted token precision application so that decimal settings are applied only when a valid deposit amount is present, enhancing transaction accuracy.

### CODE REVIEW

File: core/keysign/preSignedInputData/thor.ts [hunk 1]
```diff
@@ -34,11 +34,12 @@ export const getThorPreSignedInputData: PreSignedInputDataResolver<
         ticker: "RUNE",
         synth: false,
       }),
-      decimals: new Long(8),
+      
     });
     const toAmount = Number(keysignPayload.toAmount || "0");
     if (toAmount > 0) {
       thorchainCoin.amount = keysignPayload.toAmount;
+      thorchainCoin.decimals =  new Long(8);
```
Comment (rcoderdev) [inline core/keysign/preSignedInputData/thor.ts:42]: You can get RUNE decimals with `chainFeeCoin[Chain.ThorChain].decimals`

File: clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts [hunk 2]
```diff
@@ -85,13 +84,12 @@ export const getSwapKeysignPayloadFields = ({
         return result;
       }
 
-      const isDeposit = isFeeCoin(fromCoin);
+      const isDeposit = isFeeCoin(fromCoin) && fromCoin.chain === quote.swapChain;
```
Comment (rcoderdev) [inline clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts:87]: With this logic, the swap from MAYA.MAYA will be treated as a deposit. Is that correct?

**Review by rcoderdev — APPROVED** [review]

**Review by enriquesouza — APPROVED** [review]

File: clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts (hunk 2 above)
Comment (johnnyluo) [reply clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts:87]: There is no swap route for MAYA.MAYA token , Maya token is not liquid
