### PR TITLE
Fix: displayed network fee on tx details overview page

### LINKED ISSUE #1858: [BUG] Transaction details est. fee is suspiciously high
**Describe the bug**
Est. fee doesn't make sense to user.

**To Reproduce**
1. Go to bungee.exchange or any dApp
2. Make a transaction
3. Compare network fees

**Expected behavior**
Est. Network fee should be Transaction fee. And display the final actual Transaction Fee instead of max Gas fee.

**Screenshots**
Before making a transaction:

Image

After making the transaction

Image

Should display the final transaction fee to the user instead of theoritical max gas fee

Image

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by devzl**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1858 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [x] Sending  - Please attach a tx link here https://snowtrace.io/tx/0x97dd1eff3fa45fb71a4ff05ac2813323e0411f36fd23d4931b7afb09a02203db
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots (if applicable):
Screenshot 2025-06-19 at 15 53 05

## Summary by CodeRabbit

- **New Features**
	- Introduced new components for displaying transaction fees with enhanced formatting, including estimated and actual fees with loading and error handling.
	- Added context providers and hooks to manage and access transaction hash and keysign message payload globally.
- **Refactor**
	- Updated components to use context and hooks instead of passing transaction data via props, simplifying interfaces and improving data flow.
- **Chores**
	- Modularized fee display logic and improved internal state management for better maintainability and consistency.

### CODE REVIEW

File: core/ui/mpc/keysign/tx/KeysignTxOverview.tsx [hunk 1]
```diff
@@ -64,6 +66,33 @@ export const KeysignTxOverview = ({
     value: txHash,
   })
 
+  // Actual gas fee
+  const [actualFee, setActualFee] = useState<string | null>(null)
+
+  useEffect(() => {
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/tx/KeysignTxOverview.tsx:72]: 1. We are conducting all asynchronous operations using `use-query`.  
2. Move this functionality to a separate component and display it only for EVM chains; for other chains, keep the "Estimated Fee" label.  
3. Use `isOneOf` to check if the chain belongs to a specific group of chains.  
4. If loading the estimated fee fails, display an error, for example: `<MatchQuery error={<KeysingTxEstimatedFee/>} ...`. Therefore, we will likely have two components: one that displays the actual fee and another that shows the estimated fee.

**Review by rcoderdev — CHANGES_REQUESTED** [review]
Please address the comments

File: core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+import { useQuery } from '@tanstack/react-query'
+import { formatUnits } from 'ethers'
+
+type UseActualFeeQueryInput = {
+  txHash: string
+  chain: string
+  decimals: number
+}
+
+export const useActualFeeQuery = ({
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts:13]: Since it only works for EVM, let's rename it to `useEvmFeeQuery`. This way, the chain will be of type `EvmChain`, and we won't need the `enabled` field in the query.

File: core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  txHash,
+  chain,
+  decimals,
+}: UseActualFeeQueryInput) => {
+  return useQuery({
+    queryKey: ['actualFee', txHash, chain, decimals],
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts:19]: This hook does not need to format units or handle decimals. Instead, let's modify it to accept only the essential fields: `txHash` and `chain`. We can then propagate all arguments into the query key without listing each individual field, using the format: `queryKey: ['evmFee', input]`. The user of the query can then format the data as desired, and we will return it as a BigInt, as that is the convention for a "chain amount type."

File: core/ui/mpc/keysign/tx/components/KeysignTxFeeDisplay.tsx [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+        <Text>{networkFeesFormatted}</Text>
+      </HStack>
+    )
+  }
+
+  // For EVM chains, use the actual fee query
+  return (
+    <MatchQuery
+      value={query}
+      error={() => (
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/tx/components/KeysignTxFeeDisplay.tsx:45]: We duplicate the same thing here:

```tsx
 <HStack alignItems="center" gap={4} justifyContent="space-between">
          <Text color="shy" weight="500">
            {t('est_network_fee')}
          </Text>
          <Text>{networkFeesFormatted}</Text>
        </HStack>
```

Let's create a `KeysignTxEstimatedFee` component that will be responsible for displaying the estimated fee for non-EVM chains and in cases where we are unable to retrieve the actual fee. This component will not require any props, as it can derive its data from the state. It is intended solely for use within the context of our key-signing flow and is not designed to be reusable.

**Review by rcoderdev — CHANGES_REQUESTED** [review]
Good, left more comments

File: core/ui/mpc/keysign/tx/components/KeysignTxFeeDisplay.tsx [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+type KeysignTxFeeDisplayInput = {
+  txHash: string
+  chain: string
+  decimals: number
+  ticker: string
+  networkFeesFormatted: string | null
+}
+
+export const KeysignTxFeeDisplay = ({
```
[the remark this answers is not in the document]
Comment (rcoderdev) [reply core/ui/mpc/keysign/tx/components/KeysignTxFeeDisplay.tsx:19]: Although we can explore another approach. If we display the actual fees on other chains, we could implement an abstract `useTxFeeQuery` hook somewhere in `core/ui/chain` that throws an error for non-EVM chains. This way, in our component, we wouldn't need to check for the chain; we could simply use that query. In the event of an error, we would display the estimated fee(in MatchQuery's error handler). I believe this solution is the best option.

File: core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts (hunk 3 above)
Comment (rcoderdev) [reply core/ui/mpc/keysign/tx/queries/useActualFeeQuery.ts:19]: I believe we should proceed with this approach: https://github.com/vultisig/vultisig-windows/pull/1881/files#r2160702921. In this case, the queryKey will be ['txFee', input]. As you may have noticed, we rarely use `enabled` in queries because it introduces additional conditions in the code.

**Review by rcoderdev — APPROVED** [review]
