### PR TITLE
Fix: Advanced fee settings est network fee changes on send Flow

### LINKED ISSUE #1835: [BUG] Advanced Fee Settings break Est. network fee in send flow
**Describe the bug**
When sending tokens, the estimated network fee shown at first is correct. But when you open the Advanced Fee Settings to change the priority fee, the numbers you see for these fees are wrong and don’t match the original estimated fee.

Also, if you change the priority fee manually, the estimated network fee breaks or doesn’t update properly. This makes the fee details confusing and inconsistent.

**To Reproduce**
Initiate an AVAX send transaction.

1. Observe the estimated network fee displayed initially.
2. Click on Advanced Fee Settings.
3. Notice that max base fee and priority fee values are not consistent with the initial estimated fee.
4. Try changing the priority fee manually.
5. See that the estimated network fee becomes incorrect or breaks.

**Expected behavior**
- The advanced fee settings should show values consistent with the initially estimated network fee.
- Manual adjustments should update the estimated network fee in real-time and remain accurate.

**Screenshots**

Image
Image

### PR DESCRIPTION
**Pull request by devzl**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1835 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
  - The fee settings form now dynamically displays the fee coin ticker based on the selected network.
  - Priority fee input is shown in Gwei for easier understanding and entry.
  - Gas limit calculations now adapt to the selected fee chain instead of defaulting to Ethereum.
  - Transaction fee adjustments correctly scale fees according to the coin’s decimals for accuracy.

- **Refactor**
  - Improved handling and display of priority fee values for clarity and consistency.
  - Simplified priority fee input labeling for a cleaner user interface.
  - Enhanced fee data retrieval to provide more precise base fee information in the settings form.

### CODE REVIEW

File: clients/extension/src/pages/transaction/index.tsx [hunk 1]
```diff
@@ -235,11 +235,14 @@ export const TransactionPage = () => {
...
                                         ) {
-                                          const currentTxFee = Number(
-                                            transactionPayload.txFee
-                                          )
-                                          const totalFee = currentTxFee + fee
-
+                                          const priorityFeeInBaseUnit =
+                                            formatUnits(
+                                              BigInt(fee),
+                                              keysign.coin?.decimals || 9
```
Comment (rcoderdev) [inline clients/extension/src/pages/transaction/index.tsx:241]: Where 9 is from, you can assert that the coin (shouldBePresent) should be there.

File: core/ui/vault/send/fee/settings/evm/EvmFeeSettingsForm.tsx [hunk 2]
```diff
@@ -28,6 +30,8 @@ type EvmFeeSettingsFormProps = InputProps<EvmFeeSettingsFormValue> &
   OnCloseProp &
   OnFinishProp & {
     baseFee: number
+    chain?: EvmChain
+    coinKey?: CoinKey
```
Comment (rcoderdev) [inline core/ui/vault/send/fee/settings/evm/EvmFeeSettingsForm.tsx:34]: If you are not using coinKey, please make the chain property required.

**Review by rcoderdev — APPROVED** [review]
Address comments and free to merge
