### PR TITLE
Fix: swap on pendle

### LINKED ISSUE #1871: [BUG] Unable to swap on pendle to provide LP
**Describe the bug**
When trying to get assets on https://app.pendle.finance/ for example [mPENDLE](https://app.pendle.finance/trade/markets/0x86aacbed3e7b3d33149d5dcfd2def3c6d8498b8b/swap?view=pt&chain=arbitrum) , the approval fails due to values missing. 

**To Reproduce**
1. Go to Pendle
2. try to get mPENDLE with another asset like ARB
3. sing approval message

**Expected behavior**
Able to sign the approval message correctly and proceed.

**Screenshots**

Image

Image

**Desktop (please complete the following information):**
 - Version 0.2.1

### PR DESCRIPTION
**Pull request by devzl**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1871 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here. https://arbiscan.io/tx/0xb4e6b3b14397f76f8a174fa9920db60885828a54bfd2470587aec135e04812e1
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Improved transaction data handling to support objects containing large integer values, ensuring smoother serialization and display of blockchain transaction details across multiple chain types.

### CODE REVIEW

File: clients/extension/src/background/utils/bigIntUtils.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    return obj.map(safeJsonStringify)
+  }
+
+  if (typeof obj === 'object') {
+    const result: Record<string, unknown> = {}
+    for (const key in obj) {
+      const value = obj[key as keyof T]
+      if (typeof value === 'bigint') {
+        result[key] = value.toString()
+      } else if (key === 'type' && value === 'eip1559') {
```
Comment (rcoderdev) [inline clients/extension/src/background/utils/bigIntUtils.ts:20]: It seems inappropriate for a generic utility to contain this type of logic.

If you want to customize the serialization of specific values, you can use the following approach:

```javascript
JSON.stringify(data, (_, value) => 
    typeof value === 'bigint' ? value.toString() : value
);
```

**Review by rcoderdev — CHANGES_REQUESTED** [review]
Verify the serialization logic, doesn't feel right.
