### PR TITLE
Fix: Display successful swap green checkmark on tx overview screen

### LINKED ISSUE #1868: [BUG] Extra blank space in Overview screen
**Describe the bug**
There is extra blank space at the top of the overview screen.

**To Reproduce**
1. Go to swap
2. Make a swap (example: AVAX to zSync ETH)
3. 3. Scroll down to '....'

**Expected behavior**
Should not have the extra blank space

**Screenshots**

Image

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by devzl**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1868 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
  - Introduced a unified animation component to display transaction success messages with smooth, delayed text appearance.
- **Style**
  - Simplified and standardized the success message and animation layout across transaction screens for a cleaner user experience.

### CODE REVIEW

File: core/ui/mpc/keysign/tx/swap/SwapKeysignTxOverview.tsx [hunk 1]
```diff
@@ -91,7 +91,7 @@ export const SwapKeysignTxOverview = ({
 
   return (
     <>
-      <VStack style={{ position: 'relative' }}>
+      <VStack style={{ height: 220, position: 'relative' }} fullWidth>
```
Comment (rcoderdev) [inline core/ui/mpc/keysign/tx/swap/SwapKeysignTxOverview.tsx:94]: There are hardcoded values in two places. It might be worthwhile to move this part into a reusable component.

**Review by rcoderdev — APPROVED** [review]
Address a comment if makes sense, and free to merge
