### PR TITLE
Refactor UI of upload qr and fix camera permission

### LINKED ISSUE #1643: [BUG] Camera on send screen error
**Describe the bug**
There are a few improvements and bugs for the camera access on send screen for assets when using the extension:

- [ ] The Camera icon can't access the camera of the device and error with not able to provide permissions to access camera:

Image

- [ ] There is no back arrow on the permission error on the camera, which results in the user closing the whole extension
- [ ] The "try again" button for the camera permission does not work.

**To Reproduce**
1. Go to send screen
2. Click oncamera icon
3. See error

**Expected behavior**
Able to grant access to camera and have back arrow

**Desktop (please complete the following information):**
 - Version main screen

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

We can only request camera permission in the expanded view. If the extension is in popup mode and can't get permission, we show a button to switch to the expanded view.

Fixes #1643

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
  - Introduced a unified QR code scanning and uploading page with improved user flow.
  - Added enhanced camera permission handling with clearer guidance and error messages.
  - Added new English localization strings addressing camera access issues and expanded mode suggestions.

- **Improvements**
  - Refined the CameraIcon component for better styling flexibility and detail.
  - Streamlined QR code scanning and upload components for improved usability and layout.

- **Bug Fixes**
  - Enhanced error feedback for camera permission denial scenarios.

- **Removals**
  - Removed legacy QR code upload and scanning components, consolidating into new streamlined components.

### CODE REVIEW

File: core/ui/qr/components/CameraPermission.tsx [hunk 1]
```diff
@@ -7,28 +9,43 @@ import { extractErrorMsg } from '@lib/utils/error/extractErrorMsg'
...
-
-export const RequestCameraPermission = () => {
+export const CameraPermission = () => {
+  const { t } = useTranslation()
+  const { client, openUrl } = useCore()
   const invalidateQueries = useInvalidateQueries()
 
   const { mutate, isPending, error } = useMutation({
     mutationFn: async () => {
+      await navigator.permissions
```
Comment (rcoderdev) [inline core/ui/qr/components/CameraPermission.tsx:19]: It would be better without it; just use `const { state } = await ...`.

File: lib/ui/icons/CameraIcon.tsx [hunk 2]
```diff
@@ -1,16 +1,29 @@
-export const CameraIcon = ({ size }: { size?: number }) => (
+import { FC, SVGProps } from 'react'
+
+export const CameraIcon: FC<SVGProps<SVGSVGElement>> = ({
```
Comment (rcoderdev) [inline lib/ui/icons/CameraIcon.tsx:3]: There’s no need to add so many props. Refer to `SvgProp` in `props/index` at `lib/ui`. The only prop you may need to pass is `fontSize`, which you can do using `styles={{ fontSize: ... }}`.

Comment (rcoderdev) [reply lib/ui/icons/CameraIcon.tsx:3]: I don't believe there is a need to change `strokeLinkcap` or anything similar. If necessary, you can modify it using the `style` prop.

**Review by rcoderdev — APPROVED** [review]
Good, please address comments before merging
