### PR TITLE
Use Core Functions for Keysign Steps

### LINKED ISSUE #1018: [BUG] Refactor vulticonnect transaction construction to use the methods in core module
**Describe the bug**
Currently Vulticonnect has it's own logic to construct transaction , get prekeysign image hash
for example: 
evm - https://github.com/vultisig/vultisig-windows/blob/main/clients/extension/src/utils/transaction-provider/evm/index.ts

Please refactor vulticonnect to use the shared functions in core/keysign instead

https://github.com/vultisig/vultisig-windows/blob/main/core/keysign/preSignedInputData/evm.ts

### LINKED ISSUE #1050: Refactor Vulticonnect: Use Core Functions for Keysign Steps

### LINKED ISSUE #1130: [BUG] VultiConnect fails to sign custom messages in Fast Sign
VultiConnect is unable to sign custom messages when using **Fast Sign**, but it works correctly for **Secure Vaults**.

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
Fix #1050

Fix #1130 
**Note**: 
I used several references from `@clients/desktop` like  `KeysignMessagePayload` , `getFeeAmount`, `WalletCoreProvider` , etc. that we can move them to the  core package in another PR. 

## Summary by CodeRabbit

- **New Features**
	- Introduced new transaction handlers for various wallet types, enhancing transaction standardization and processing.
	- Added functions for improved signature encoding and transaction signing across multiple blockchain networks.
	- Added a new method for retrieving coin information based on a key.
	- Added a new method for constructing standardized transaction details based on wallet type.
	- Introduced a new method for obtaining a keysign payload for transactions.

- **Refactor**
	- Streamlined wallet integration using hooks for better performance and clarity.
	- Enhanced error handling and transaction payload construction, simplifying user interactions.
	- Simplified address provider access and transaction handling logic.
	- Refactored transaction handling logic to reduce redundancy and improve maintainability.

- **Bug Fixes**
	- Updated error messages for clarity during vault settings updates.
	- Removed an obsolete error message from localization.

- **Chores**
	- Removed legacy token support and outdated API endpoints.
	- Deleted unused files and methods to clean up the codebase.
	- Updated TypeScript configuration to remove unnecessary linting options.

### CODE REVIEW

File: clients/extension/src/background/index.ts [hunk 1]
```diff
@@ -78,14 +77,17 @@ const handleOpenPanel = (name: string): Promise<number> => {
...
 }
 
-const handleProvider = (chain: Chain, update?: boolean) => {
+const handleProvider = (chain: Chain, update?: boolean): boolean => {
   const rpc = chainRpcUrl[chain]
-  if (!rpc) return
-  if (update && rpcProvider) {
-    rpcProvider = new JsonRpcProvider(rpc)
-    return
+  if (rpc) {
```
Comment (johnnyluo) [inline clients/extension/src/background/index.ts:82]: Honestly , I like the previously one better ,  nest `if` is always harder to read

File: clients/extension/src/background/index.ts [hunk 2]
```diff
@@ -590,14 +577,15 @@ const handleRequest = (
           const [param] = params
 
           if (param?.chainId) {
-            const chainFromId = getChainByChainId(param.chainId)
-            const supportedChain = isSupportedChain(chainFromId)
-              ? chainFromId
+            const supportedChain = isSupportedChain(
+              getChainByChainId(param.chainId)
```
Comment (johnnyluo) [inline clients/extension/src/background/index.ts:581]: I don't understand this change either , the previous version , you all `getChainByChainId` once , 

the current one , you call it twice back to back , I think the previous one is much better

File: clients/extension/src/pages/popup/index.tsx [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import '@clients/extension/src/styles/index.scss'
 import '@clients/extension/src/pages/popup/index.scss'
 
+import { WalletCoreProvider } from '@clients/desktop/src/providers/WalletCoreProvider'
```
Comment (johnnyluo) [inline clients/extension/src/pages/popup/index.tsx:4]: not a good idea to directly refer to a provider in desktop

File: clients/extension/src/pages/popup/pages/main/index.tsx [hunk 4]
```diff
@@ -140,11 +130,11 @@ const Component = () => {
   const showReloadMessage = () => {
     messageApi.open({
       type: 'info',
-      content: t(messageKeys.RELOAD_MESSAGE),
+      content: t(t(messageKeys.RELOAD_MESSAGE)),
```
Comment (johnnyluo) [inline clients/extension/src/pages/popup/pages/main/index.tsx:133]:
```suggestion
      content: t(messageKeys.RELOAD_MESSAGE),
```

File: clients/extension/src/background/index.ts (hunk 1 above)
Comment (Ehsan-saradar) [reply clients/extension/src/background/index.ts]: Resolved

File: clients/extension/src/background/index.ts (hunk 2 above)
Comment (Ehsan-saradar) [reply clients/extension/src/background/index.ts]: Done

File: clients/extension/src/pages/popup/index.tsx (hunk 3 above)
Comment (Ehsan-saradar) [reply clients/extension/src/pages/popup/index.tsx:4]: I will fix it in another PR

File: clients/extension/src/pages/popup/pages/main/index.tsx (hunk 4 above)
Comment (Ehsan-saradar) [reply clients/extension/src/pages/popup/pages/main/index.tsx]: Done

File: clients/extension/src/pages/popup/index.tsx (hunk 3 above)
Comment (Ehsan-saradar) [reply clients/extension/src/pages/popup/index.tsx:4]: https://github.com/vultisig/vultisig-windows/issues/1129

**Review by johnnyluo — APPROVED** [review]
LGTM
