### PR TITLE
Fix swap doesn't have to address issue

### LINKED ISSUE #1020: [BUG] THORChain Swap EVM failed
**Describe the bug**
Trying to swap some BNB -> RUNE through THORChain , it failed with the following error

Image

The TO Address in swap is invalid

### PR DESCRIPTION
**Pull request by johnnyluo**
fixes #1020

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced swap transaction processing by refining the deposit detection criteria to ensure that deposits are correctly identified.
  - Adjusted output handling so that deposit transactions accurately bypass receiving an address, leading to improved reliability in swap operations.

### CODE REVIEW

File: clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts [hunk 1]
```diff
@@ -85,13 +84,12 @@ export const getSwapKeysignPayloadFields = ({
         return result;
       }
 
-      const isDeposit = isFeeCoin(fromCoin);
+      const isDeposit = isFeeCoin(fromCoin) && fromCoin.chain === quote.swapChain;
```
Comment (rcoderdev) [inline clients/desktop/src/chain/swap/keysign/getSwapKeysignPayloadFields.ts:87]: It seems to be the same as https://github.com/vultisig/vultisig-windows/pull/1024#discussion_r1958985461

**Review by rcoderdev — APPROVED** [review]
