### PR TITLE
Fix import issue in mac

### LINKED ISSUE #1736: [BUG] Extension closes on import
**Describe the bug**
On some browsers it is impossible to import a vault share. As soon as the window to select the vault share from the folder opens, the extension closes and it is impossible to import any vault.

Affected browsers:
- Arc browser (windows)
- Brave browser (Linux)
- possibly more

**To Reproduce**
1. Open extension
2. Go to import vault
3. Select vault share
4. See error and window closing

**Expected behavior**
Window stays open so user can successfully import their vault.

**Desktop (please complete the following information):**
 - Version 0.2.0

**Additional context**
Possibly is affected that the extension does not safe the state where it is in and always resets to main screen when closing.

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #1736

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **New Features**
	- Added an Import Vault view to both the desktop and extension applications, allowing users to access vault import functionality.
	- Introduced a guard in the extension to prompt users to continue in a new window when importing a vault in certain popup scenarios.

- **Bug Fixes**
	- Improved navigation handling by updating how the Import Vault view is managed between shared and app-specific views.

- **Chores**
	- Updated dependencies by adding ua-parser-js to the extension.
	- Cleaned up configuration files by removing unused scripts and updating import paths for consistency.

### CODE REVIEW

File: clients/extension/src/components/expand-view-guard/index.tsx [hunk 1]
```diff
@@ -0,0 +1,45 @@
+import { isPopupView } from '@clients/extension/src/utils/functions'
+import { useCore } from '@core/ui/state/core'
+import { VStack } from '@lib/ui/layout/Stack'
+import { PageContent } from '@lib/ui/page/PageContent'
+import { Text } from '@lib/ui/text'
+import { FC, ReactNode, useEffect, useState } from 'react'
+import { useTranslation } from 'react-i18next'
+import { UAParser } from 'ua-parser-js'
+
+interface ExpandViewGuardProps {
```
Comment (rcoderdev) [inline clients/extension/src/components/expand-view-guard/index.tsx:10]: We prefer using `type` instead of `interface`.

**Review by rcoderdev — APPROVED** [review]
Good, small comment to address
